name: monkey_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  csv: ^5.1.1
  permission_handler: ^11.3.0
  excel: ^2.1.0

  # State management & architecture
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^8.0.3
  equatable: ^2.0.5

  # Network
  dio: ^5.8.0+1
  connectivity_plus: ^5.0.1
  flutter_screenutil: ^5.9.0

  # ✅ Firebase (كلها متوافقة من نفس الجيل)
  firebase_core: ^4.2.0
  firebase_auth: ^6.0.3
  cloud_firestore: ^6.0.3
  firebase_analytics: ^12.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^17.1.2

  # UI & Design
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  http: ^1.5.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  animate_do: ^3.0.2
  loading_indicator: ^3.1.0
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0

  # Routing & localization
  go_router: ^12.1.3
  easy_localization: ^3.0.7+1

  # Utils
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  rename: ^3.1.0
  intl: ^0.20.2

  # Launcher icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/translations/
    - assets/screenshot/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/monkey_white.png"
